import 'package:asrdb/localization/keys.dart';

class LocalizedAl {
  static final Map<String, String> localizedStrings = {
    Keys.save: 'Ruaj',
    Keys.close: 'Mbyll',
    Keys.login: 'Hyr',
    Keys.cancel: 'Anullo',
    Keys.proceed: 'Vijo',
    Keys.enterMail: 'Vendosni email',
    Keys.mailPlaceholder: 'Email',
    Keys.passwordPlaceholder: 'Fjalëkalimi',
    Keys.enterPassword: 'Vendosni fjalëkalimin',
    Keys.outsideMunicipality:
        'Verifikoni koordinatat, pasi rezultojnë të jenë jashtë bashkisë për të cilën jeni të autorizuar.',
    Keys.overlapingBuildings:
        'Ndërtesa e hedhur ka mbivendosje me një ndërtesë ekzistuese.',
    Keys.finishReviewWarning:
        'Nuk mund të vazhdoni pa kryer fillimisht verifikimin e ndërtesës.',
    Keys.dwellingUpdated:
        'Të dhënat e njësisë së banimit u shtuan dhe u ruajtën me sukses.',
    Keys.dwellingCouldNotUpdated:
        'Nuk u arrit të shtohet njësia e banimit. Ju lutemi, provoni përsëri',
    Keys.basemapTerrain: 'Terren',
    Keys.basemapEsriSatellite: 'ESRISatelit',
    Keys.basemapAsig2025: 'ASIG 2025 Satelit',
    Keys.download: 'Shkarko',
    Keys.startReviewingTitle: 'Fillo Rishikimin',
    Keys.startReviewingContent:
        'Jeni i sigurt që doni të filloni rishikimin e kësaj ndërtese?',
    Keys.finishReviewingTitle: 'Perfundo Rishikimin',
    Keys.finishReviewingContent:
        'Jeni i sigurt që doni të përfundoni rishikimin e kësaj ndërtese?',
    Keys.manageDwellings: 'Menaxho Banesat',
    Keys.dwellings: 'Banesat',
    Keys.floor: 'Kati',
    Keys.noApartment: 'Pa Numer',
    Keys.goBack: 'Kthehu',
    Keys.dwellingTotalLabel: '{count} gjithsej',
    Keys.dwellingCountSingle: '{count} banesë',
    Keys.dwellingCountPlural: '{count} banesa',
    Keys.notAvailable: 'Pa të dhëna',
    Keys.apartmentNumber: 'Ap. {number}',
    Keys.unknown: 'E panjohur',
    Keys.issues: 'Probleme',
    Keys.noDwellingsFound: 'Nuk u gjetën banesa',
    Keys.addFirstDwellingPrompt: 'Shtoni banesën e parë për të filluar',
    Keys.dwellingQualityComplete: 'E plotësuar',
    Keys.dwellingQualityIncomplete: 'E paplotë',
    Keys.dwellingQualityConflicted: 'Në konflikt',
    Keys.dwellingQualityUntested: 'E patestuar',
    Keys.dwellingQualityDeleted: 'E fshirë',
    Keys.validateData: 'Valido të Dhënat',
    Keys.validateDataUntestedData:
        'Validimi nuk mund të kryhet. Ndërtesa është validuar më parë (BldQuality != 9).',
    Keys.startReviewing: 'Fillo Rishikimin',
    Keys.finishReviewing: 'Përfundo Rishikimin',
    Keys.finishReviewingSuccess: 'Mbyllja e rishikimit perfundoi me sukses',
    Keys.legend: 'Legjenda',
    Keys.legendBuildings: 'Ndertesat',
    Keys.legendEntrances: 'Hyrjet',
    Keys.confirmationTitle: 'Konfirmim',
    Keys.confirmationContent: 'Jeni i sigurt që doni të vazhdoni?',
    Keys.confirmationCancel: 'Anulo',
    Keys.confirmationConfirm: 'Konfirmo',
    Keys.successGeneral: "Të gjitha ndryshimet u aplikuan me sukses.",
    Keys.finishValidateWarning:
        "Ju lutem, verifikoni elementët përbërës të ndërtesës.",
    Keys.finishValidateSuccess:
        "Validimi perfundoi me sukses. Komponentet perberes te nderteses nuk kane nevoje per kontroll.",
    Keys.invalidShape:
        "Forma e hedhur nuk është e vlefshme. Ju lutemi, provoni përsëri.",
    Keys.successAddBuilding: "Ndertesa u shtua me sukses.",
    Keys.successUpdateBuilding: "Ndertesa u përditësua me sukses.",
    Keys.successAddEntrance: "Hyrja u shtua me sukses.",
    Keys.successUpdateEntrance: "Hyrja u përditësua me sukses.",
    Keys.entranceDistanceValidationError: "Hyrja duhet të jetë brenda {distance} metrave nga ndërtesa",
    Keys.successAddDwelling: "Apartamenti u shtua me sukses.",
    Keys.successUpdateDwelling: "Apartamenti u përditësua me sukses.",
    Keys.startValidationSuccess: "Nisja e validimit u krye me sukses",
    Keys.startValidationWarning: "Nisja e validimit nuk u krye.",
    Keys.intersectionDetected: "Mbivendosje ndertesash",
    Keys.intersectionMessage:
        "Ndertesa e zgjedhur ka mbivendosje me nje ndertese tjeter. Doni te vijoni me ruajtjen?",
    Keys.fieldWorkNotOpened: "Puna ne terrent nuk eshte nisur.",
    Keys.blReviewWarning :"Per ndertesen e zgjedhur nuk kerkohet rishikim ose ka nje rishikim te rihapur (BldReview != 6 && BldReview!=5).",
    Keys.blReviewNoPending : "Ndertesa e zgjedhur nuk ka statusin e rishikimit ne pritje. (BldReview = 4)",
    Keys.backToMap: 'Kthehu te Harta',
    Keys.buildingReviewTitle: 'Rishikimi i Ndërtesave',
    Keys.buildingReviewFilterAll: 'Të Gjitha',
    Keys.buildingReviewFilterNeedsReview: 'Ri hapur / Rishikim',
    Keys.loadingMapOverlay: 'Duke ngarkuar shtresën e hartës...',
    Keys.errorLoadingOverlay: 'Gabim gjatë ngarkimit të shtresës',
    Keys.noImageDataAvailable: 'Nuk ka të dhëna imazhi',
    // Settings page translations
    Keys.settings: 'Cilësimet',
    Keys.dataManagement: 'Menaxhimi i të Dhënave',
    Keys.updateAndManageData: 'Përditëso dhe menaxho të dhënat e aplikacionit',
    Keys.updateJsonAttributes: 'Përditëso Atributet JSON',
    Keys.updateJsonAttributesDesc: 'Shkarko dhe përditëso skedarët e atributeve të ndërtesave, hyrjeve dhe banesave',
    Keys.updateSchemaFiles: 'Përditëso Skedarët e Skemës',
    Keys.updateSchemaFilesDesc: 'Shkarko dhe përditëso skedarët e përkufizimit të skemës',
    Keys.information: 'Informacioni',
    Keys.settingsInfoText: 'Përdorni këto opsione për të përditësuar skedarët tuaj lokalë me informacionin më të fundit nga serveri.',
    Keys.jsonAttributesUpdatedSuccess: 'Atributet JSON u përditësuan me sukses',
    Keys.jsonAttributesUpdateFailed: 'Dështoi përditësimi i atributeve JSON',
    Keys.schemaFilesUpdatedSuccess: 'Skedarët e skemës u përditësuan me sukses',
    Keys.schemaFilesUpdateFailed: 'Dështoi përditësimi i skedarëve të skemës',
    // Logout translations
    Keys.logout: 'Dil',
    Keys.logoutSubtitle: 'Dil nga llogaria juaj',
    Keys.logoutConfirmation: 'Konfirmo Daljen',
    Keys.logoutConfirmationMessage: 'Jeni i sigurt që doni të dilni?',
    Keys.logoutSuccess: 'U dol me sukses',
    Keys.fieldRequired: '{fieldName} duhet plotesuar',
    Keys.logoutError: 'Dështoi dalja',
    
    // Side menu translations
    Keys.mobileApp: 'Mobile',
    Keys.viewMaps: 'Shiko Hartat',
    Keys.viewMapsSubtitle: 'Hartat e shkarkuara offline',
    Keys.settingsSubtitle: 'Konfigurimi i aplikacionit',
    Keys.streetLoadError: 'Gabim gjatë ngarkimit të rrugëve',
    Keys.streetLoading: 'Duke kërkuar rrugë...',
    Keys.streetEmpty: 'Nuk u gjetën rrugë',
    Keys.townLoadError: 'Gabim gjatë ngarkimit të qyteteve',
    Keys.townLoading: 'Duke ngarkuar qytetet...',
    Keys.townEmpty: 'Nuk u gjetën qytete',
    Keys.profile: 'Profili',
    Keys.profileSubtitle: 'Detajet e llogarisë së përdoruesit',
    Keys.userInformation: 'Informacioni i Përdoruesit',
    Keys.tokenInformation: 'Informacioni i Token-it',
    Keys.userId: 'ID e Përdoruesit',
    Keys.role: 'Roli',
    Keys.municipalityId: 'ID e Bashkisë',
    Keys.email: 'Email',
    Keys.issuedAt: 'Lëshuar Më',
    Keys.expiresAt: 'Skadon Më',
    Keys.issuer: 'Lëshuesi',
    Keys.audience: 'Audienca',
    Keys.helpSupport: 'Ndihmë & Mbështetje',
    Keys.helpSupportSubtitle: 'Merrni ndihmë',
    Keys.homeSubtitle: 'Faqja Kryesore',
    Keys.homeTitle: 'Kryefaqja',
    
    // Add/View/Edit form titles
    Keys.add: 'Shto',
    Keys.view: 'Shiko',
    Keys.edit: 'Ndrysho',
    Keys.building: 'Ndërtesën',
    Keys.entrance: 'Hyrjen',
    Keys.dwelling: 'Banesën',
    Keys.viewDetails: 'Shiko Detajet',
    Keys.viewAndEdit: 'Shiko dhe Ndrysho',
    Keys.addNew: 'Shto të Re',
    Keys.addFirstDwelling: 'Shto Banesën e Parë',
    Keys.streetTypeLabel: 'Tipi',
    Keys.streetIdLabel: 'ID',
    Keys.entranceFarWarning:
        'Kujdes! Hyrja e lidhur me këtë ndërtesë mund të jetë e pozicionuar larg saj.',
    Keys.comments: 'Komente',
    Keys.sectionTitle: '',
    Keys.sectionIdentification: 'Variabla Identifikuese',
    Keys.sectionDescription: 'Variabla Përshkruese',
    Keys.fieldWorkOverview: 'Përmbledhje Terreni',
    Keys.fieldWorkOverviewSubtitle: 'Përmbledhje Terreni',
    
    // Offline map translations
    Keys.ok: 'OK',
    Keys.delete: 'Fshi',
    Keys.refresh: 'Rifresko',
    Keys.dismiss: 'Mbyll',
    Keys.downloadOfflineData: 'Shkarko të Dhëna Offline',
    Keys.downloadAreaInfo: 'Informacioni i Zonës së Shkarkimit',
    Keys.downloadDetails: 'Detajet e Shkarkimit:',
    Keys.downloadName: 'Emri i Shkarkimit:',
    Keys.enterDownloadName: 'Vendosni një emër për këtë shkarkim',
    Keys.downloadNameHint: 'Ky emër do të përdoret për të identifikuar të dhënat e shkarkuara.',
    Keys.downloading: 'Po shkarkohet...',
    Keys.zoomInToDownload: 'Zmadho për të Shkarkuar',
    Keys.downloadData: 'Shkarko të Dhëna',
    Keys.downloadedAreas: 'Zonat e Shkarkuara',
    Keys.deleteDownloadedData: 'Fshi të Dhënat e Shkarkuara',
    Keys.deleteConfirmMessage: 'Jeni i sigurt që doni të fshini "{areaName}"?\n\nKjo do të heqë përgjithmonë të gjitha të dhënat e ndërtesave, hyrjeve dhe banesave për këtë zonë. Ky veprim nuk mund të kthehet prapa.',
    Keys.applyArea: 'Aplikoni Zonën',
    Keys.synchronize: 'Sinkronizo',
    Keys.downloaded: 'E Shkarkuar',
    Keys.user: 'Përdoruesi',
    Keys.lastSync: 'Sinkronizimi i Fundit',
    Keys.never: 'Kurrë',
    Keys.loadingDownloadedAreas: 'Duke ngarkuar zonat e shkarkuara...',
    Keys.noOfflineAreas: 'Nuk u gjetën zona offline',
    Keys.downloadSomeAreas: 'Shkarkoni disa zona për t\'i parë këtu',
    Keys.hasPendingSync: 'Ka artikuj që presin sinkronizim',
    Keys.offlineDataDownloader: 'Shkarkuesi i të Dhënave Offline',
    Keys.showDownloadInfo: 'Shfaq informacionin e shkarkimit',
    Keys.currentZoom: 'Zmadhimi Aktual:',
    Keys.downloadArea: 'Zona e Shkarkimit:',
    Keys.north: 'Veri:',
    Keys.south: 'Jug:',
    Keys.east: 'Lindje:',
    Keys.west: 'Perëndim:',
    Keys.zoomInLevel: 'Zmadho në nivel {level} ose më lart për të zgjedhur zonën e shkarkimit',
    Keys.error: 'Gabim',
    Keys.pageNotFound: 'Faqja nuk u gjet!',
    Keys.fieldWorkActive: 'Puna në Terren Aktive',
    Keys.fieldWorkInactive: 'Puna në Terren Joaktive',
    Keys.status: 'Statusi:',
    Keys.active: 'Aktiv',
    Keys.fieldWorkNotOpenedMessage: 'Puna në terren nuk është hapur ende. Ju lutemi, filloni një seancë pune në terren për të parë detajet.',
    Keys.problemOccurred: 'Ka ndodhur një problem',
    Keys.buildings: 'Ndërtesat:',
    Keys.area: 'Zona:',
    Keys.errorDeletingData: 'Gabim në fshirjen e të dhënave: {error}',
    Keys.started: 'Filluar:',
    Keys.entranceCreationMode: 'Modaliteti i Krijimit të Hyrjes',
    Keys.entranceEditMode: 'Modaliteti i Redaktimit të Hyrjes',
    Keys.buildingCreationMode: 'Modaliteti i Krijimit të Ndërtesës',
    Keys.buildingEditMode: 'Modaliteti i Redaktimit të Ndërtesës',
    Keys.useOffline: 'Përdor Offline',
    Keys.firstTimeLogin: 'Hyrja e Parë / Harrova Fjalëkalimin',
    Keys.firstTimeLoginUrlNotConfigured: 'URL-ja e hyrjes për herë të parë nuk është konfiguruar',
    Keys.invalidUrl: 'URL e pavlefshme: {url}',
    Keys.couldNotLaunchUrl: 'Nuk u arrit të hapej URL-ja',
    Keys.errorOpeningUrl: 'Gabim gjatë hapjes së URL-së: {error}',
    Keys.otp: 'Pin një perdorimësh',
    Keys.enterOtp: 'Vendosni pin-in një perdorimësh',
    Keys.resend: 'Ridergoni',
    Keys.submit: 'Dërgo',
    Keys.backToLogin: 'Kthehu te Hyrja',
    Keys.verify: 'Verifiko',
    Keys.resendIn: 'Përsendoni pas {seconds} sekondash',
    Keys.forgotPasswordTitle: 'Rivendosni Fjalëkalimin',
    Keys.forgotPasswordDescription: 'Vendosni adresën tuaj të email-it për të marrë linkun e rivendosjes së fjalëkalimit.',
    Keys.forgotPasswordSuccess: 'Email-i për rivendosjen e fjalëkalimit u dërgua me sukses!',
    Keys.invalidEmail: 'Ju lutemi, vendosni një adresë të vlefshme email.',
    Keys.shareBuilding: 'Ndaje Ndërtesën',
    Keys.buildingId: 'ID e Ndërtesës',
  };
}
