import 'package:asrdb/localization/keys.dart';

class LocalizedEn {
  static final Map<String, String> localizedStrings = {
    Keys.save: 'Save',
    Keys.close: 'Close',
    Keys.login: 'Login',
    Keys.cancel: 'Cancel',
    Keys.proceed: 'Proceed',
    Keys.enterMail: 'Enter email',
    Keys.mailPlaceholder: 'Email',
    Keys.passwordPlaceholder: 'Password',
    Keys.enterPassword: 'Enter password',
    Keys.outsideMunicipality:
        'Please verify the coordinates, as they appear to be outside the municipality you are authorized for.',
    Keys.overlapingBuildings:
        'The newly added building overlaps with an existing building.',
    Keys.finishReviewWarning:
        'You can\'t proceed without first validating the building.',
    Keys.dwellingUpdated:
        'The dwelling information was successfully updated and saved.',
    Keys.dwellingCouldNotUpdated:
        'Dwelling could not be updated. Check your input and try again.',
    Keys.dwellingAdded:
        'The dwelling information was successfully added and saved.',
    Keys.dwellingCouldNotAdd:
        'Dwelling could not be added. Check your input and try again.',
    Keys.basemapTerrain: 'Terrein',
    Keys.basemapEsriSatellite: 'ESRI Satellite',
    Keys.basemapAsig2025: 'ASIG 2025 Satellite',
    Keys.download: 'Download',
    Keys.startReviewingTitle: 'Start Reviewing',
    Keys.startReviewingContent:
        'Are you sure you want to start reviewing this building?',
    Keys.finishReviewingTitle: 'Finish Reviewing',
    Keys.finishReviewingContent:
        'Are you sure you want to finish reviewing this building?',
    Keys.manageDwellings: 'Manage Dwellings',
    Keys.dwellings: 'Dwellings',
    Keys.floor: 'Floor',
    Keys.noApartment: 'No Number',
    Keys.goBack: 'Go Back',
    Keys.dwellingTotalLabel: '{count} total',
    Keys.dwellingCountSingle: '{count} dwelling',
    Keys.dwellingCountPlural: '{count} dwellings',
    Keys.notAvailable: 'N/A',
    Keys.apartmentNumber: 'Apt {number}',
    Keys.unknown: 'Unknown',
    Keys.issues: 'Issues',
    Keys.noDwellingsFound: 'No dwellings found',
    Keys.addFirstDwellingPrompt: 'Add your first dwelling to get started',
    Keys.dwellingQualityComplete: 'Complete',
    Keys.dwellingQualityIncomplete: 'Incomplete',
    Keys.dwellingQualityConflicted: 'Conflicted',
    Keys.dwellingQualityUntested: 'Untested',
    Keys.dwellingQualityDeleted: 'Deleted',
    Keys.validateData: 'Validate Data',
    Keys.validateDataUntestedData:
        'Validation cannot be performed. The building has already been validated (BldQuality ≠ 9).',
    Keys.startReviewing: 'Start Reviewing',
    Keys.finishReviewing: 'Finish Reviewing',
    Keys.legend: 'Legend',
    Keys.legendBuildings: 'Buildings',
    Keys.legendEntrances: 'Entrances',
    Keys.confirmationTitle: 'Confirmation',
    Keys.confirmationContent: 'Are you sure you want to proceed?',
    Keys.confirmationCancel: 'Cancel',
    Keys.confirmationConfirm: 'Confirm',
    Keys.successGeneral: "All changes were applied successfully.",
    Keys.finishValidateWarning:
        "Please verify the structural components of the building.",
    Keys.finishValidateSuccess:
        "Validation completed successfully. The building’s component elements do not require further checks.",
    Keys.invalidShape: "The drawn shape is not valid. Please try again.",
    Keys.successAddBuilding: "Building was successfully added.",
    Keys.successUpdateBuilding: "Building was successfully updated.",
    Keys.successAddEntrance: "Entrance was successfully added.",
    Keys.successUpdateEntrance: "Entrance was successfully updated.",
    Keys.entranceDistanceValidationError:
        "Entrance must be within {distance} meters of the building",
    Keys.successAddDwelling: "Dwelling was successfully added.",
    Keys.successUpdateDwelling: "Dwelling was successfully updated.",
    Keys.startValidationSuccess: "Validation started successfully",
    Keys.startValidationWarning: "Validation could not be started.",
    Keys.finishReviewingSuccess: 'Finish reviewing finished successfully',
    Keys.intersectionDetected: "Intersection detected",
    Keys.intersectionMessage:
        "Selected building has an intersection with another one. Do you want to continue and save it?",
    Keys.fieldWorkNotOpened: "Field work not started yet.",
    Keys.blReviewWarning:
        "The selected building does not require review or has a reopened review (BldReview != 6 && BldReview != 5).",
    Keys.blReviewNoPending:
        "The selected building does not have the review status pending. (BldReview = 4)",
    Keys.backToMap: 'Back to Map',
    Keys.buildingReviewTitle: 'Building Review',
    Keys.buildingReviewFilterAll: 'All',
    Keys.buildingReviewFilterNeedsReview: 'Reopened / Needs Review',
    Keys.loadingMapOverlay: 'Loading map overlay...',
    Keys.errorLoadingOverlay: 'Error Loading Overlay',
    Keys.noImageDataAvailable: 'No image data available',
    // Settings page translations
    Keys.settings: 'Settings',
    Keys.dataManagement: 'Data Management',
    Keys.updateAndManageData: 'Update and manage application data',
    Keys.updateJsonAttributes: 'Update JSON Attributes',
    Keys.updateJsonAttributesDesc:
        'Download and update building, entrance, and dwelling attribute files',
    Keys.updateSchemaFiles: 'Update Schema Files',
    Keys.updateSchemaFilesDesc: 'Download and update schema definition files',
    Keys.information: 'Information',
    Keys.settingsInfoText:
        'Use these options to update your local data files with the latest information from the server.',
    Keys.jsonAttributesUpdatedSuccess: 'JSON attributes updated successfully',
    Keys.jsonAttributesUpdateFailed: 'Failed to update JSON attributes',
    Keys.schemaFilesUpdatedSuccess: 'Schema files updated successfully',
    Keys.schemaFilesUpdateFailed: 'Failed to update schema files',
    // Logout translations
    Keys.logout: 'Logout',
    Keys.logoutSubtitle: 'Sign out',
    Keys.logoutConfirmation: 'Confirm Logout',
    Keys.logoutConfirmationMessage: 'Are you sure you want to logout?',
    Keys.logoutSuccess: 'Logged out successfully',
    Keys.fieldRequired: '{fieldName} must be filled',
    Keys.logoutError: 'Logout failed',

    // Side menu translations
    Keys.mobileApp: 'Mobile',
    Keys.viewMaps: 'View Maps',
    Keys.viewMapsSubtitle: 'Downloaded offline maps',
    Keys.settingsSubtitle: 'App configuration',
    Keys.streetLoadError: 'Error loading streets',
    Keys.streetLoading: 'Searching streets...',
    Keys.streetEmpty: 'No streets found',
    Keys.townLoadError: 'Error loading towns',
    Keys.townLoading: 'Loading towns...',
    Keys.townEmpty: 'No towns found',
    Keys.profile: 'Profile',
    Keys.profileSubtitle: 'User account details',
    Keys.userInformation: 'User Information',
    Keys.tokenInformation: 'Token Information',
    Keys.userId: 'User ID',
    Keys.role: 'Role',
    Keys.municipalityId: 'Municipality ID',
    Keys.email: 'Email',
    Keys.issuedAt: 'Issued At',
    Keys.expiresAt: 'Expires At',
    Keys.issuer: 'Issuer',
    Keys.audience: 'Audience',
    Keys.helpSupport: 'Help & Support',
    Keys.helpSupportSubtitle: 'Get assistance',
    Keys.homeSubtitle: 'Home Page',
    Keys.homeTitle: 'Homepage',

    // Add/View/Edit form titles
    Keys.add: 'Add',
    Keys.view: 'View',
    Keys.edit: 'Edit',
    Keys.building: 'Building',
    Keys.entrance: 'Entrance',
    Keys.dwelling: 'Dwelling',
    Keys.viewDetails: 'View Details',
    Keys.viewAndEdit: 'View and Edit',
    Keys.addNew: 'Add New',
    Keys.addFirstDwelling: 'Add First Dwelling',
    Keys.streetTypeLabel: 'Type',
    Keys.streetIdLabel: 'ID',
    Keys.entranceFarWarning:
        'Heads up! The entrance linked to this building may be positioned far from the building.',
    Keys.comments: 'Comments',
    Keys.sectionTitle: '',
    Keys.sectionIdentification: 'Identification',
    Keys.sectionDescription: 'Description',
    Keys.fieldWorkOverview: 'Fieldwork Overview',
    Keys.fieldWorkOverviewSubtitle: 'Fieldwork Overview',
    
    // Offline map translations
    Keys.ok: 'OK',
    Keys.delete: 'Delete',
    Keys.refresh: 'Refresh',
    Keys.dismiss: 'Dismiss',
    Keys.downloadOfflineData: 'Download Offline Data',
    Keys.downloadAreaInfo: 'Download Area Info',
    Keys.downloadDetails: 'Download Details:',
    Keys.downloadName: 'Download Name:',
    Keys.enterDownloadName: 'Enter a name for this download',
    Keys.downloadNameHint: 'This name will be used to identify the downloaded data.',
    Keys.downloading: 'Downloading...',
    Keys.zoomInToDownload: 'Zoom in to Download',
    Keys.downloadData: 'Download Data',
    Keys.downloadedAreas: 'Downloaded Areas',
    Keys.deleteDownloadedData: 'Delete Downloaded Data',
    Keys.deleteConfirmMessage: 'Are you sure you want to delete "{areaName}"?\n\nThis will permanently remove all buildings, entrances, and dwellings data for this area. This action cannot be undone.',
    Keys.applyArea: 'Apply Area',
    Keys.synchronize: 'Synchronize',
    Keys.downloaded: 'Downloaded',
    Keys.user: 'User',
    Keys.lastSync: 'Last Sync',
    Keys.never: 'Never',
    Keys.loadingDownloadedAreas: 'Loading downloaded areas...',
    Keys.noOfflineAreas: 'No offline areas found',
    Keys.downloadSomeAreas: 'Download some areas to see them here',
    Keys.hasPendingSync: 'Has items pending synchronization',
    Keys.offlineDataDownloader: 'Offline Data Downloader',
    Keys.showDownloadInfo: 'Show download info',
    Keys.currentZoom: 'Current Zoom:',
    Keys.downloadArea: 'Download Area:',
    Keys.north: 'North:',
    Keys.south: 'South:',
    Keys.east: 'East:',
    Keys.west: 'West:',
    Keys.zoomInLevel: 'Zoom in to level {level} or higher to select download area',
    Keys.error: 'Error',
    Keys.pageNotFound: 'Page not found!',
    Keys.fieldWorkActive: 'Field Work Active',
    Keys.fieldWorkInactive: 'Field Work Inactive',
    Keys.status: 'Status:',
    Keys.active: 'Active',
    Keys.fieldWorkNotOpenedMessage: 'Field work is not opened yet. Please start a field work session to view details.',
    Keys.problemOccurred: 'A problem occurred',
    Keys.buildings: 'Buildings:',
    Keys.area: 'Area:',
    Keys.errorDeletingData: 'Error deleting data: {error}',
    Keys.started: 'Started:',
    Keys.entranceCreationMode: 'Entrance Creation Mode',
    Keys.entranceEditMode: 'Entrance Edit Mode',
    Keys.buildingCreationMode: 'Building Creation Mode',
    Keys.buildingEditMode: 'Building Edit Mode',
    Keys.useOffline: 'Use Offline',
    Keys.firstTimeLogin: 'First Login / Forgot Password',
    Keys.firstTimeLoginUrlNotConfigured: 'First time login URL is not configured',
    Keys.invalidUrl: 'Invalid URL: {url}',
    Keys.couldNotLaunchUrl: 'Could not launch the URL',
    Keys.errorOpeningUrl: 'Error opening URL: {error}',
    Keys.otp: 'One time pin',
    Keys.enterOtp: 'Enter one time pin',
    Keys.resend: 'Resend',
    Keys.submit: 'Submit',
    Keys.backToLogin: 'Back to Login',
    Keys.verify: 'Verify',
    Keys.resendIn: 'Resend in {seconds} seconds',
    Keys.forgotPasswordTitle: 'Reset Password',
    Keys.forgotPasswordDescription: 'Enter your email address to receive a password reset link.',
    Keys.forgotPasswordSuccess: 'Password reset email sent successfully!',
    Keys.invalidEmail: 'Please enter a valid email address.',
    Keys.shareBuilding: 'Share Building',
    Keys.buildingId: 'Building ID',
    
    // Point deletion
    Keys.polygonMinPointsError: 'Polygon must have at least 4 points to delete a point.',
    Keys.deletePointTitle: 'Delete Point?',
    Keys.deletePointConfirmation: 'Are you sure you want to delete this point? This action can be undone.',
    Keys.cannotDeletePointError: 'Cannot delete point: polygon must have at least 4 points',
  };
}
